---
title: "03-Exon-level-expression"
output: html_document
date: "2024-04-11"
---

```{r}
BiocManager::install("EBSEA")
library(EBSEA)
```

https://bioconductor.org/packages/release/bioc/vignettes/EBSEA/inst/doc/EBSEA.html

```{r}

```

```{r}
# data = t(exon.counts.ts)

exon.info <- exon.counts %>% colnames() %>% 
  as.data.frame() %>% set_names("sample_name") %>%
  left_join(sample.info) %>% 
  column_to_rownames("sample_name")
all(row.names(exon.info) == colnames(t(exon.counts.ts)))

exon.info.0 <- exon.info %>% filter(temperature == c("9", "0")) %>% ungroup() %>% droplevels()
exon.info.5 <- exon.info %>% filter(temperature==c("9", "5")) %>% ungroup() %>% droplevels()
exon.info.16 <- exon.info %>% filter(temperature==c("9", "16")) %>% ungroup() %>% droplevels()

exon.counts.filt <- EBSEA::filterCounts(exon.counts)

print(paste("# exons before filtering:", nrow(exon.counts)))
print(paste("# exons remaining after pre-filtering:", nrow(exon.counts.filt)))
print(paste("# of exons dropped:", nrow(exon.counts) - nrow(exon.counts.filt), sep=" "))
print(paste("% of fragments remaining after pre-filtering: ", signif(100*sum(exon.counts.filt)/sum(exon.counts), digits = 5), "%", sep=""))
print(paste("Number of fragments dropped: ", signif(sum(exon.counts)-sum(exon.counts.filt), digits = 5)))
print(paste("% of fragments dropped: ", signif(100*(sum(exon.counts)-sum(exon.counts.filt))/sum(exon.counts), digits = 5), "%", sep=""))
print(paste("Number of fragments remaining: ", signif(sum(exon.counts.filt), digits = 5)))

ebsea.out.0 <- EBSEA::EBSEA(exon.counts.filt[,c(rownames(exon.info.0))], exon.info.0, ~temperature)
ebsea.out.5 <- EBSEA::EBSEA(exon.counts.filt[,c(rownames(exon.info.5))], exon.info.5, ~temperature)
ebsea.out.16 <- EBSEA::EBSEA(exon.counts.filt[,c(rownames(exon.info.16))], exon.info.16, ~temperature)

ebsea.out.0$ExonTable %>% filter(padj<0.05) %>% filter(gene_id=="132464016")  #number diff. expressed exons 
ebsea.out.0$GeneTable %>% filter(padj<0.05) %>% filter(Gene=="132464016") # number diff. expressed genes 
EBSEA::visualizeGenes("132464016", ebsea.out.0)
save(ebsea.out.0, file = "../ebsea/ebsea.out.0")

ebsea.out.5$ExonTable %>% filter(padj<0.05) 
ebsea.out.5$GeneTable %>% filter(padj<0.05) 

ebsea.out.16$ExonTable %>% filter(padj<0.05) 
ebsea.out.16$GeneTable %>% filter(padj<0.05) 
```
```{r}
paste("Number of DEGs in COLD treatment according to EBSEA: ", ebsea.out.0$GeneTable %>% filter(padj<0.05) %>% nrow())
paste("No. that are also DEGs according to DESeq2: ", ebsea.out.0$GeneTable %>% filter(padj<0.05) %>% filter(Gene %in% c(rownames(diffex.0) %>% gsub("GeneID:", "", .))) %>% nrow())
paste("No. that are also DEGs according to DESeq2 after tank-effect filting : ", ebsea.out.0$GeneTable %>% filter(padj<0.05) %>% filter(Gene %in% c(rownames(diffex.0.filt) %>% gsub("GeneID:", "", .))) %>% nrow())
print(" ")
paste("Number of DEGs in COOL treatment according to EBSEA: ", ebsea.out.5$GeneTable %>% filter(padj<0.05) %>% nrow())
paste("No. that are also DEGs according to DESeq2: ", ebsea.out.5$GeneTable %>% filter(padj<0.05) %>% filter(Gene %in% c(rownames(diffex.5) %>% gsub("GeneID:", "", .))) %>% nrow())
paste("No. that are also DEGs according to DESeq2 after tank-effect filting : ", ebsea.out.5$GeneTable %>% filter(padj<0.05) %>% filter(Gene %in% c(rownames(diffex.5.filt) %>% gsub("GeneID:", "", .))) %>% nrow())
print(" ")
paste("Number of DEGs in WARM treatment according to EBSEA: ", ebsea.out.16$GeneTable %>% filter(padj<0.05) %>% nrow())
paste("No. that are also DEGs according to DESeq2: ", ebsea.out.16$GeneTable %>% filter(padj<0.05) %>% filter(Gene %in% c(rownames(diffex.16) %>% gsub("GeneID:", "", .))) %>% nrow())
paste("No. that are also DEGs according to DESeq2 after tank-effect filting : ", ebsea.out.16$GeneTable %>% filter(padj<0.05) %>% filter(Gene %in% c(rownames(diffex.16.filt) %>% gsub("GeneID:", "", .))) %>% nrow())
```
Generate consensus 

```{r}
degs.cons.0 <- 
  Reduce(intersect, list(
  rownames(ebsea.out.0$GeneTable %>% filter(padj<0.05)), 
  c(rownames(diffex.0.filt) %>% gsub("GeneID:", "", .))))

degs.cons.5 <- 
  Reduce(intersect, list(
  rownames(ebsea.out.5$GeneTable %>% filter(padj<0.05)), 
  c(rownames(diffex.5.filt) %>% gsub("GeneID:", "", .))))

degs.cons.16 <- 
  Reduce(intersect, list(
  rownames(ebsea.out.16$GeneTable %>% filter(padj<0.05)), 
  c(rownames(diffex.16.filt) %>% gsub("GeneID:", "", .))))

length(degs.cons.0)
length(degs.cons.5)
length(degs.cons.16)
```


Generate .tab file with lists of DEGs in response to each temperature for DAVID enrichment analysis

Using Uniprot SPIDs

```{r}
ebsea.4David.uniprot <- list(

  "Cold (0degC)" = 
    res.0 %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(abs(select(., contains("log2FoldChange")))>0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.0$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),
  
  "Cool (5degC)" = 
    res.5 %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(abs(select(., contains("log2FoldChange")))>0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.5$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),
  
  "Warm (16degC)" = 
    res.16 %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(abs(select(., contains("log2FoldChange")))>0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.16$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),

  "Cold_Downregulated"  =
    res.0  %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(select(., contains("log2FoldChange"))< -0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.0$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),
  
  "Cold_Upregulated" = 
    res.0  %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(select(., contains("log2FoldChange"))> 0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.0$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),
  
  "Cool_Downregulated" = 
    res.5  %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(select(., contains("log2FoldChange"))> 0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.5$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),
  
  "Cool_Upregulated" = 
    res.5  %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(select(., contains("log2FoldChange"))< -0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.5$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),

  "Warm_Downregulated" = 
    res.16 %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(select(., contains("log2FoldChange"))< -0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.16$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector(),
  
  "Warm_Upregulated" = 
    res.16  %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    filter(select(., contains("log2FoldChange"))> 0.5) %>%
    filter(ncbi_id %in% rownames(ebsea.out.16$GeneTable %>% filter(padj<0.05))) %>% 
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector())

# Write tab-delimited file with each column containing Uniprot IDs for each set of DEGs 
write_delim(x = ldply(ebsea.4David.uniprot, rbind) %>% t() %>% as.data.frame(), delim = "\t", col_names = F, na="", 
            file = "../ebsea/ebsea-4David.uniprot.txt")
            
# BACKGROUND - all genes submitted to DESeq2 analysis 
res.5 %>% as.data.frame() %>% rownames_to_column("ncbi_id") %>% mutate(ncbi_id=gsub("GeneID:", "", ncbi_id)) %>%
    left_join(pcod.blast) %>%
    dplyr::select(spid) %>% na.omit() %>% unlist() %>% as.vector() %>% write_clip() 
```